version: '3.11'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/backend
      
    depends_on:
      - db


    env_file:
      - ./.env


  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: postgres:14.8-alpine

    volumes:
      - postgres_data:/var/lib/postgresql/data

    env_file:
      - ./.env   


volumes:
  postgres_data:
